version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8.0
    container_name: personQueue
    ports:
      - 5672:5672
      - 15672:15672
  graphite:
    image: graphiteapp/docker-graphite-statsd
    container_name: graphite
    ports:
      - 80:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000


