version: '3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: drone-elastic
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
  mongo:
    image: mongo:4.2
    container_name: drone-mongo
    ports:
      - 27017:27017
